steps:
  # 1. Install Dependencies & Run Backend Tests
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r services/sentinel-growth/requirements.txt
        pip install pytest pytest-asyncio
        export PYTHONPATH=services/sentinel-growth
        python -m pytest services/sentinel-growth/tests

  # 2. Build Dashboard (Frontend)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd services/vesper-gtm/dashboard
        npm install
        npm run build

  # 3. Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sentinel-growth'
      - '--source'
      - 'services/sentinel-growth'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY